### ISSUE TITLE
TClinbraryVersion page link to Git hub sources and not to readable table for Lib

### ISSUE THREAD

**Issue by flabb17** [RumstiBumsti/TcLibraryVersions#32]
![image](https://github.com/user-attachments/assets/d83cb985-3e5c-4604-9621-f11618d02e72)
This table is growing and hard to read only on the "github previsualisation" page

Is it possible to (as the other sub.pages) display it directyl on the web site ?

**Comment by RumstiBumsti** [comment]
this page is not from me
